# Attack directions
UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3

# Loot tiers
TIER_0 = 0
TIER_1 = 1
TIER_2 = 2
TIER_3 = 3
TIER_4 = 4
TIER_5 = 5

MUSIC_VOLUME = 0.5
SFX_VOLUME = 0.2

FRAMERATE = 60

DIALOGUE = {
    1: ["This is the first time I have tried journaling, so let's",
        "see how this turns out. My name is Noah Frogman.",
        "I am accompanied by my two companions, Simon",
        "the Alchemist and Mary the Warrior. I am the",
        "Leader of the party. We heard that this dungeon",
        "had a powerful elixir at its core, so we aim to",
        "find it.", "      Noah"],
    2: ["On floor 2 we ran into another group. I tried to",
        "talk with them, but the only thing they",
        "would talk about was how much money they",
        "would make from selling the elixir. When I realized",
        "there was no point in talking to them and left",
        "they started yelling at us to leave the elixir",
        "in their hands. What an odd group."],
    3: ["Last night while we were sleeping, the group",
        "we met yesterday suddenly attacked us.",
        "Simon was injured quite badly before Mary",
        "managed to fend them off. We managed to find",
        "a potion lying around, which helped, but we",
        "need to find something better or else Simon",
        "will die."],
    4: ["Apparently there is a strange monster on the",
        "next floor that will drop and item capable",
        "of healing Simon. It's quite the dangerous",
        "adversary, but we need some sort of hope to",
        "hold on to. It's better than continuing to",
        "fight the crazy adventures on this floor."],
    5: ["We found the monster and it really dropped",
        "the item. Simon ate it and has already been",
        "fully healed. He says he feels even stronger",
        "than he did before he was attacked. It's",
        "truly a miracle. We can now focus on finding",
        "the elixir."],
    6: ["The dungeon seems to only be getting more",
        "dangerous. The sixth floor has been filled with",
        "traps, and the adventurers here are even more",
        "hostile than before. Some of the are wielding",
        "strange weapons of the like I've never seen.",
        "The ones with icicle like blades are the",
        "most terrifying. They trap you by conjuring",
        "a wall of ice before attacking you non-stop."],
    7: ["It seems strange how many chests there are",
        "full of weapons. Each floor we find more and",
        "powerful weapons. Why in the world would a",
        "dungeon be full of so many weapons? All the",
        "other insane adventurers keep finding them",
        "and attacking us.",
        "It's almost like the dungeon wants us to kill",
        "each other."],
    8: ["Mary just stepped on a trap and died.",
        "It happened so quickly, Simon and I couldn't",
        "even help her. I don't know what we are going",
        "to do now... Simon said we should keep going",
        "deeper. If we find the elixir it might bring",
        "Mary back. I know it's insane, but what else",
        "are we going to do?"],
    9: ["Simon has been researching the potions that",
        "have been scattered everywhere. He's discovered",
        "that the potions have a remarkably similar",
        "structure to blood.",
        "I can't believe I've been drinking them the whole",
        "time. I want to stop drinking them, but how else",
        "am I going to survive?"],
    10: ["Another one of monsters we found on floor five",
         "appeared. While fighting it, I noticed some strange",
         "green growths on it. I had through it was just",
         "moss but it was pulsating in a fashion that",
         "makes that totally impossible. What is going",
         "on in this dungeon?"],
    11: ["Simon found a potion full of Mary's blood.",
         "I- I don't. What is this dungeon? It's brought",
         "out the worst of all the adventurers, made them",
         "fight and supplied them with weapons. Then the",
         "blood from these fights and these traps turn",
         "into potions that tempt us to climb deeper into",
         "this hell?!? I regret ever stepping foot into",
         "this place."],
    12: ["The enemies are only getting stronger.",
         "Honestly, the only reason I can keep leading",
         "is Simon. He really believes we'll still be",
         "able to save Mary. I'm tired. There are so,",
         "so, many enemies."],
    13: ["This morning I woke up and Simon was gone.",
         "Well, he was still here, but he wasn't the"
         "same. There are green growths on his arms,",
         "and his spirits are down. He's yelling at me to",
         "leave him behind, to find the elixir and save",
         "Mary."],
    14: ["Simon's face has morphed into something monstrous.",
         "His skin has turned hard and rocky, and the",
         "green growths have taken over. He doesn't talk",
         "anymore, and he just wanders aimlessly. We",
         "just need to make it to the next floor."],
    15: ["Simon has lost control. He attacked me.",
         "Mary is dead, Simon is... not dead, but",
         "definitely not alive. I have to leave Simon",
         "behind. I am alone now.",
         "I just need to make it to the next floor."],
    16: ["I don't know why I decided to lead this",
         "expedition anymore. At first, it was the money.",
         "The elixir is worth enough money to live like",
         "a king for all of time..."],
    17: ["...then, after Mary died, It felt like all",
         "my dreams and ambitions came crashing down.",
         "It wasn't about the money anymore. I just",
         "wanted to bring her back to life. But, without",
         "Simon I doubt I could have kept going.",
         "I lost all confidence in myself as a leader..."],
    18: ["...and when Simon, changed, no, died, I...",
         "I broke. No money, or elixir could bring back",
         "the things the dungeon took from me. The",
         "dungeon has eaten it all up."],
    19: ["If only we could meet again.",
         "Goodbye.",
         "     Noah Frogman"]
}

